# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d46b29eaca084f733270fb70f6152401f28ec0153b821c68d31f06616912ee187c3e09f3575ce8710750fc96d854f701835746b28885bc6a53477d441b622746

test:
  secret_key_base: 71899a707851bd54af7b7db13e747771d225ca2c2e0200eb51a2610ad09831a58e7df9926242e8eeb6513d9ddd35b1d6195387c8d4fe361a014de6ee4546654d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
